apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "formal-eks-external-secret-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.type }}
  target:
    name: formal-eks-secret
  data:
  - secretKey: formal-snowflake-proxy-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.snowflakeProxyKeyName }}
  {{- if .Values.deployDataClassifierSatellite }}
  - secretKey: formal-data-classifier-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.dataClassifierSatelliteKeyName }}
  {{- end }}
  {{- if .Values.deployDataDiscovery }}
  - secretKey: formal-data-discovery-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.dataDiscoveryKeyName }}
  {{- end }}
  