{{- if .Values.secretStore.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.secretStore.type }}
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccount }}
{{- end }}