# snowflake-sidecar-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "snowflake-sidecar-app-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": formal-external-snowflake
    "app.kubernetes.io/instance": formal-external-snowflake
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      "app.kubernetes.io/name": formal-external-snowflake
      "app.kubernetes.io/instance": formal-external-snowflake
  template:
    metadata:
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        "app.kubernetes.io/name": formal-external-snowflake
        "app.kubernetes.io/instance": formal-external-snowflake
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.containers.snowflakeSidecar.name }}
          image: {{ .Values.containers.snowflakeSidecar.image }}
          ports:
            - containerPort: 2379
              name: etcd-api
            - containerPort: 2380
              name: etcd-peer
          envFrom:
            - configMapRef:
                name: {{ printf "snowflake-sidecar-config-%s" .Release.Name }}
          resources:
            {{ toYaml .Values.containers.snowflakeSidecar.resources | nindent 12 }}
          env:
            - name: FORMAL_CONTROL_PLANE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: formal-eks-secret
                  key: formal-snowflake-proxy-api-key
---
{{- if .Values.deployDataDiscovery }}
# data-discovery-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "data-discovery-app-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": formal-external-discovery
    "app.kubernetes.io/instance": formal-external-discovery
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      "app.kubernetes.io/name": formal-external-discovery
      "app.kubernetes.io/instance": formal-external-discovery
  template:
    metadata:
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        "app.kubernetes.io/name": formal-external-discovery
        "app.kubernetes.io/instance": formal-external-discovery
    spec:
      containers:
        - name: {{ .Values.containers.dataDiscovery.name }}
          image: {{ .Values.containers.dataDiscovery.image }}
          ports:
            - containerPort: 443
              name: egress
          envFrom:
            - configMapRef:
                name: {{ printf "data-discovery-config-%s" .Release.Name }}
          resources:
            {{ toYaml .Values.containers.dataDiscovery.resources | nindent 12 }}
          env:
            - name: FORMAL_CONTROL_PLANE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: formal-eks-secret
                  key: formal-data-discovery-api-key
{{- end }}