[tools]
# mise itself
usage = "latest"
pipx = "latest"

# general
buf = "1.53.0"
terraform = "1.11.4"

# golang
revive = "1.3.7"
"go:github.com/daixiang0/gci" = "0.13.4"
"go:golang.org/x/tools/cmd/goimports" = "0.23.0"
"go:mvdan.cc/gofumpt" = "0.6.0"

[settings]
jobs = 1
experimental = true

[tasks."pre-commit"]
depends = ["lint", "tidy", "format", "docs"]