[tools]
# mise itself
usage = "latest"
pipx = "latest"

# general
buf = "1.53.0"

# golang
revive = "1.3.7"
"go:github.com/daixiang0/gci" = "0.13.4"
"go:golang.org/x/tools/cmd/goimports" = "0.23.0"
"go:mvdan.cc/gofumpt" = "0.6.0"
"go:connectrpc.com/connect/cmd/protoc-gen-connect-go" = "1.16.2"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "2.20.0"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "1.34.2"
"go:github.com/pressly/goose/v3/cmd/goose" = "3.22.1"

[settings]
jobs = 1
experimental = true

[tasks."pre-commit"]
depends = ["lint", "tidy", "format", "docs"]