apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "bigquery-sidecar-config-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configMaps.bigQuerySidecar }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
---
{{- if .Values.deployDataClassifierSatellite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "data-classifier-satellite-config-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configMaps.dataClassifierSatellite }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}