apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "formal-eks-external-secret-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ printf "formal-eks-secret-store-%s" .Release.Name }}
    kind: SecretStore
  target:
    name: formal-eks-secret
  data:
  - secretKey: formal-bigquery-proxy-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.bigQueryProxyKeyName }}
  {{- if .Values.deployDataClassifierSatellite }}
  - secretKey: formal-data-classifier-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.dataClassifierSatelliteKeyName }}
  {{- end }}
  