#!/bin/bash
# mise sources=["**/*.go"]
# mise outputs=[".mise/.outputs/format"]
set -e

# if gci is not installed, install it
if ! command -v gci &> /dev/null; then
    mise install "go:github.com/daixiang0/gci"
fi

# if goimports is not installed, install it
if ! command -v goimports &> /dev/null; then
    mise install "go:golang.org/x/tools/cmd/goimports"
fi

# if gofumpt is not installed, install it
if ! command -v gofumpt &> /dev/null; then
    mise install "go:mvdan.cc/gofumpt"
fi

mise x -- gci write -s standard -s default -s "prefix(github.com/formalco)" $(git ls-files | grep '\.go$' | grep -v '/gen/')
mise x -- goimports -w -local "github.com/formalco" $(git ls-files | grep '\.go$' | grep -v '/gen/')
mise x -- gofumpt -w $(git ls-files | grep '\.go$' | grep -v '/gen/')

touch .mise/.outputs/format
