replicaCount: 1
sidecars: 
  # s3:
  #   containers:
  #     name: s3-sidecar-app
  #     image: 
  #     resources: {}
  #   configMap:
  #       CLIENT_LISTEN_TLS: "false"
  #       SERVER_CONNECT_TLS: "false"
  #       DATA_CLASSIFIER_SATELLITE_URI: "localhost:50055"
  #       CUSTOMER_TLS_CERT_PRIVATE_KEY: ""
  #       CUSTOMER_TLS_CERT_FULLCHAIN: ""
  #       PII_SAMPLING_RATE: "8"
  #   podSelector:
  #     matchLabels:
  #       app:  formal-external
  #     labels:
  #       app:  formal-external
  #   externalSecrets:
  #     s3ProxyKeyName: app/production/formal-external/formal-s3-proxy-api-key
  http:
    containers:
      name: http-sidecar-app
      image: 
      resources: {}
    configMap:
      CLIENT_LISTEN_TLS: "false"
      SERVER_CONNECT_TLS: "false"
      DATA_CLASSIFIER_SATELLITE_URI: "localhost:50055"
      CUSTOMER_TLS_CERT_PRIVATE_KEY: ""
      CUSTOMER_TLS_CERT_FULLCHAIN: ""
      PII_SAMPLING_RATE: "8"
      STRIP_VALUES_FROM_LOGS: "false"
      LOGGED_HTTP_PAYLOAD_MAX_SIZE: "5000000"
      HEALTH_CHECK_ON_TRAFFIC_PORT: "true"
      HEALTH_CHECK_ON_TRAFFIC_PORT_PATH: "/health"
    podSelector:
      matchLabels:
        app:  formal-external
      labels:
        app:  formal-external
    externalSecrets:
      secretKey: formal-http-proxy-api-key
      keyName : app/production/formal-external/formal-http-proxy-api-key
secretManagerRegion: us-west-2
serviceAccountDeployment: external-secrets-irsa-role-test
podAnnotations: {}
