replicaCount: 1
containers:
  sidecar:
    name: http-sidecar-app
    image: 
    resources: {}
  dataClassifierSatellite:
    name: data-classifier-satellite-app
    image: 
    resources: {}
configMaps:
  sidecar:
    CLIENT_LISTEN_TLS: "false"
    SERVER_CONNECT_TLS: "false"
    DATA_CLASSIFIER_SATELLITE_URI: "localhost:50055"
    CUSTOMER_TLS_CERT_PRIVATE_KEY: ""
    CUSTOMER_TLS_CERT_FULLCHAIN: ""
    PII_SAMPLING_RATE: "8"
    STRIP_VALUES_FROM_LOGS: "false"
    LOGGED_HTTP_PAYLOAD_MAX_SIZE: "5000000"
    HEALTH_CHECK_ON_TRAFFIC_PORT: "true"
    HEALTH_CHECK_ON_TRAFFIC_PORT_PATH: "/health"
  dataClassifierSatellite:
    PII_DETECTION: formal
podSelector:
  matchLabels:
    appName:  formal-external
    instance:  formal-external-web
  labels:
    appName:  formal-external
    instance:  formal-external-web
secretStoreServiceAccount: external-secrets-irsa
secretStore:
  deploy: true
  name: formal-eks-secret-store-formal-http-helm-chart
  region: us-west-2
  type: SecretStore
  serviceAccount: formal-external-secrets-irsa
deployDataClassifierSatellite: false
externalSecrets:
  keyName: formal-http-proxy-api-key
  proxyKeyName : formal-http-proxy-tls-cert
serviceAccountDeployment: external-secrets-irsa
podAnnotations: {}
