replicaCount: 1
containers:
  httpSidecar:
    name: http-sidecar-app
    image: 
    resources: {}
  dataClassifierSatellite:
    name: data-classifier-satellite-app
    image: 
    resources: {}
configMaps:
  httpSidecar:
    CLIENT_LISTEN_TLS: "false"
    SERVER_CONNECT_TLS: "false"
    DATA_CLASSIFIER_SATELLITE_URI: "localhost:50055"
    CUSTOMER_TLS_CERT_PRIVATE_KEY: ""
    CUSTOMER_TLS_CERT_FULLCHAIN: ""
    PII_SAMPLING_RATE: "8"
    STRIP_VALUES_FROM_LOGS: "false"
    LOGGED_HTTP_PAYLOAD_MAX_SIZE: "5000000"
    HEALTH_CHECK_ON_TRAFFIC_PORT: "true"
    HEALTH_CHECK_ON_TRAFFIC_PORT_PATH: "/health"
  dataClassifierSatellite:
    PII_DETECTION: formal
podSelector:
  matchLabels:
    app:  formal-external
  labels:
    app:  formal-external
secretManagerRegion: ap-southeast-2
deployDataClassifierSatellite: false
externalSecrets:
  httpProxyKeyName : app/production/formal-external/formal-http-proxy-tls-cert
serviceAccountDeployment: value
podAnnotations: {}
