{{- if .Values.deploySecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretManagerRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStoreServiceAccount }}
{{- end }}