apiVersion: v1
kind: Service
metadata:
  name: postgres-sidecar-service
  namespace: {{ .Release.Namespace }}
  annotations:
  {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    "app.kubernetes.io/name": formal-external
    "app.kubernetes.io/instance": formal-external-web
  ports:
    - port: {{ .Values.service.port }}
      name: sidecar
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - port: 8080
      name: healthcheck
      targetPort: 8080
      protocol: TCP
    