apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "formal-eks-external-secret-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.type }}
  target:
    name: {{ printf "formal-eks-secret-%s" .Release.Name }}
  data:
  - secretKey: {{ .Values.externalSecrets.kubernetesSidecar.keyName }}
    remoteRef:
      key: {{ .Values.externalSecrets.kubernetesSidecar.proxyKeyName }}
