replicaCount: 1
containers:
  postgresSidecar:
    name: postgres-sidecar-app
    image: 
    resources: {}
  dataClassifierSatellite:
    name: data-classifier-satellite-app
    image: 
    resources: {}
configMaps:
  postgresSidecar:
    CLIENT_LISTEN_TLS: "false"
    SERVER_CONNECT_TLS: "false"
    DATA_CLASSIFIER_SATELLITE_URI: "localhost:50055"
    CUSTOMER_TLS_CERT_PRIVATE_KEY: ""
    CUSTOMER_TLS_CERT_FULLCHAIN: ""
    PII_SAMPLING_RATE: "8"
  dataClassifierSatellite:
    PII_DETECTION: formal
podSelector:
  matchLabels:
    app: formal-external
  labels:
    app:  formal-external
deployDataClassifierSatellite: false
secretStore:
  deploy: true
  name: formal-eks-secret-store
  region: us-east-1
  type: SecretStore
  serviceAccount: formal-external-secrets-irsa
  targetName: formal-eks-secret
externalSecrets:
  postgresProxyKeyName: formal-postgres-proxy-api-key
service:
  type: LoadBalancer
  port: 5432
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
podAnnotations: {}
