apiVersion: v1
kind: ConfigMap
metadata:
  name: http-sidecar-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configMaps.httpSidecar }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-classifier-satellite-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configMaps.dataClassifierSatellite }}
  {{ $key }}: "{{ $value }}"
  {{- end }}