apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "formal-eks-external-secret-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: formal-eks-secret-store
    kind: SecretStore
  target:
    name: formal-eks-secret
  data:
  - secretKey: formal-http-proxy-tls-cert
    remoteRef:
      key: {{ .Values.externalSecrets.httpProxyKeyName }}
  {{- if .Values.deployDataClassifierSatellite }}
  - secretKey: formal-data-classifier-tls-cert
    remoteRef:
      key: {{ .Values.externalSecrets.dataClassifierSatelliteKeyName }}
  {{- end }}
  