apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: formal-eks-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretManagerRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: formal-external-secrets-irsa