apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: formal-eks-external-secret
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: formal-eks-secret-store
    kind: SecretStore
  target:
    name: formal-eks-secret
  data:
  - secretKey: formal-http-proxy-tls-cert
    remoteRef:
      key: formal-http-proxy-tls-cert
      property: key
  - secretKey: formal-data-classifier-tls-cert
    remoteRef:
      key: formal-data-classifier-tls-cert
      property: key