apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: formal-eks-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretManagerRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStoreServiceAccount }}