apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "formal-eks-external-secret-%s" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.type }}
  target:
    name: {{ printf "formal-eks-secret-%s" .Release.Name }}
  data:
  {{- if .Values.deployHttpSidecar }}
  - secretKey: {{ .Values.externalSecrets.httpSidecar.keyName }}
    remoteRef:
      key: {{ .Values.externalSecrets.httpSidecar.proxyKeyName }}
  {{- end }}
  {{- if .Values.deployS3Sidecar }}
  - secretKey: {{ .Values.externalSecrets.s3Sidecar.keyName }}
    remoteRef:
      key: {{ .Values.externalSecrets.s3Sidecar.proxyKeyName }}
  {{- end }}
  {{- if .Values.deployDataClassifierSatellite }}
  - secretKey: formal-data-classifier-tls-cert
    remoteRef:
      key: {{ .Values.externalSecrets.dataClassifierSatelliteKeyName }}
  {{- end }}
  