replicaCount: 1
containers:
  mysqlSidecar:
    name: mysql-sidecar-app
    image: 
    resources: {}
  dataClassifierSatellite:
    name: data-classifier-satellite-app
    image: 
    resources: {}
configMaps:
  mysqlSidecar:
    CLIENT_LISTEN_TLS: "false"
    SERVER_CONNECT_TLS: "false"
    DATA_CLASSIFIER_SATELLITE_URI: "localhost:50055"
    CUSTOMER_TLS_CERT_PRIVATE_KEY: ""
    CUSTOMER_TLS_CERT_FULLCHAIN: ""
    PII_SAMPLING_RATE: "8"
  dataClassifierSatellite:
    PII_DETECTION: formal
podSelector:
  matchLabels:
    app: formal-external
  labels:
    app:  formal-external
secretManagerRegion: us-east-1
deployDataClassifierSatellite: false
deploySecretStore: true
secretStoreServiceAccount: formal-external-secrets-irsa
externalSecrets:
  mysqlProxyKeyName: formal-mysql-proxy-api-key
service:
  type: LoadBalancer
  port: 3306
podAnnotations: {}