apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "connector.fullname" . }}-ecr-cred-init
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  {{- include "connector.ecrJob" . | nindent 2 }}
