apiVersion: v1
kind: ServiceAccount
metadata:
  name: formal-ecr-secret-manager
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"  # Run before the ECR job (-10)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: formal-ecr-secret-manager
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"  # Run before the ECR job (-10)
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "get"]
    resourceNames: ["formal-ecr-secret"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: formal-ecr-secret-manager
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"  # Run before the ECR job (-10)
subjects:
  - kind: ServiceAccount
    name: formal-ecr-secret-manager
roleRef:
  kind: Role
  name: formal-ecr-secret-manager
  apiGroup: rbac.authorization.k8s.io
