{{- if .Values.googleServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connector.fullname" . }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.googleServiceAccount }}
{{- end }}
