{{- range $key, $val := .Values.sidecars }}
{{- if $val.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $val.containers.name .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": {{ $val.podSelector.labels.app }}
    "app.kubernetes.io/instance": {{ printf "%s-%s" $val.podSelector.labels.app .Release.Name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
        {{- toYaml $val.podSelector.matchLabels | nindent 8 }}
  template:
    metadata:
      annotations: {{ toYaml $.Values.podAnnotations | nindent 8 }}
      labels:
        {{- toYaml $val.podSelector.labels | nindent 8 }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccountDeployment }}
      containers:
      - name: {{ $val.containers.name }}
        image: {{ $val.containers.image }}
        envFrom:
          - configMapRef:
              name: {{ printf "%s-config-%s" $val.containers.name $.Release.Name }}
        resources:
          {{ toYaml $val.containers.resources | nindent 10 }}
        env:
        - name: FORMAL_CONTROL_PLANE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ printf "formal-eks-secret-%s" $.Release.Name }}
              key: {{ $key }}-tls-cert
      restartPolicy: Always
---
{{- end }}
{{- end }}
