{{- range $sidecarKey, $sidecarVal := .Values.sidecars }}
{{- if $sidecarVal.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret-%s" $sidecarKey $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ printf "formal-eks-secret-store-%s" $.Release.Name }}
    kind: SecretStore
  target:
    name: {{ printf "%s-secret-%s" $sidecarKey $.Release.Name }}
  data:
  - secretKey: {{ $sidecarVal.externalSecrets.secretKey }}
    remoteRef:
      key: {{ $sidecarVal.externalSecrets.keyName }}
---
{{- end }}
{{- end }}
