{{- range $sidecarKey, $sidecarVal := .Values.sidecars }}
{{- if and $sidecarVal.deploy (isset $sidecarVal "externalSecrets") }}
{{- range $secretIndex, $secretVal := $sidecarVal.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret-%s-%d" $sidecarKey .Release.Name $secretIndex }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ printf "formal-eks-secret-store-%s" .Release.Name }}
    kind: SecretStore
  target:
    name: {{ printf "%s-secret-%s-%d" $sidecarKey .Release.Name $secretIndex }}
  data:
  - secretKey: {{ $secretVal.secretKey }}
    remoteRef:
      key: {{ $secretVal.keyName }}
---
{{- end }}
{{- end }}
{{- end }}
