apiVersion: v1
kind: Service
metadata:
  name: snowflake-sidecar-service-nlb
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
spec:
  type: {{ .Values.service.type }}
  selector:
    "app.kubernetes.io/name": formal-external-snowflake
    "app.kubernetes.io/instance": formal-external-snowflake
  ports:
    - port: {{ .Values.service.port }}
      name: sidecar
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - port: 8080
      name: healthcheck
      targetPort: 8080
      protocol: TCP
    - port: 2379
      name: etcd-api
      targetPort: 2379
      protocol: TCP
    - port: 2380
      name: etcd-peer
      targetPort: 2380
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: snowflake-sidecar-service-cluster-ip
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      name: healthcheck
      targetPort: 8080
    - port: 2379
      name: etcd-api
      targetPort: 2379
    - port: 2380
      name: etcd-peer
      targetPort: 2380
---
{{- if .Values.deployDataDiscovery }}
# data-discovery-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: data-discovery-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    "app.kubernetes.io/name": formal-external-discovery
    "app.kubernetes.io/instance": formal-external-discovery
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}
---
{{- if .Values.deployDataDiscovery }}
# data-discovery-nlb.yaml
apiVersion: v1
kind: Service
metadata:
  name: data-discovery-service-nlb
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
spec:
  type: {{ .Values.service.type }}
  selector:
    "app.kubernetes.io/name": formal-external-discovery
    "app.kubernetes.io/instance": formal-external-discovery
  ports:
    - port: 443
      name: egress
      targetPort: 443
      protocol: TCP
    - port: 8080
      name: healthcheck
      targetPort: 8080
      protocol: TCP
{{- end }}